id: P004565
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W23683
  title: དཔལ་ལྡན་འབྲུག་པ་དཀར་བརྒྱུད་པའི་གཞི་ལམ་འབྲས་གསུམ་གྱི་རྣམ་གཞག་མདོར་བསྡུས།
  author: ''
  volumes:
    f620732791324b05aaea8408b4227356:
      image_group_id: I2431
      title: ''
      volume_number: 1
      total_pages: 74
      base_file: v001.txt
